### ISSUE TITLE
Problem with date format

### ISSUE THREAD

**Issue by matias-yii** [EAnushan/yii2-datetime-compare#2]
I have a problem with the date format. The validator doesn't work for certain formats. I made a pull request with the changes. Thanks.

**Comment by EAnushan** [comment]
Thank you, I'll take a look at it this afternoon.

**Comment by EAnushan** [comment]
I made some comments on your pull request. Other than those minor comments, the functionality looks good. I'll merge it once everything is cleaned up.

**Comment by matias-yii** [comment]
Done. I made a new pull request. Thanks.

**Comment by EAnushan** [comment]
Thank you! I added some minor comments. You should be able to just make the changes on your branch without creating a pull request. I believe the pull request will be updated automatically if you push to your repository.
